# vim: noexpandtab

[[snippet]]
key = 'thunk'
description = 'function without args'
body = '''
function()
	$0
end
'''

[[snippet]]
key = 'vimx'
description = 'require vim-artemis'
body = '''
local vimx = require('artemis')
'''

