#!/bin/bash -u
if [[ -e molt ]]; then
  exit
fi
rm -f deno.json
deno add @molt/cli
cat > molt << EOF
#!/bin/bash -u
deno run -A $(cat deno.json | grep -Po 'jsr[^"]+') "\$@"
EOF
chmod +x molt
cp molt ~/cmd/molt
rm -f deno.json
