[[plugins]]
repo = 'https://github.com/ibhagwan/fzf-lua'
on_cmd = 'FzfLua'
on_lua = 'fzf-lua'

[[plugins]]
repo = 'https://github.com/monaqa/dial.nvim'
on_map = '<Plug>(dial'
lua_add = '''
vim.keymap.set('n', '<C-a>', '<Plug>(dial-increment)')
vim.keymap.set('n', '<C-x>', '<Plug>(dial-decrement)')
'''
hook_source = '''
source $VIMDIR/conf/plug/nvim/dial.lua
'''

[[plugins]]
repo = 'https://github.com/lewis6991/gitsigns.nvim'

[[plugins]]
repo = 'https://github.com/stevearc/oil.nvim'
on_lua = 'oil'
on_cmd = 'Oil'
lua_source = '''
require('oil').setup {
  default_file_explorer = false,
}
'''

[[plugins]]
repo = 'NeogitOrg/neogit'
on_cmd = 'Neogit'
lua_source = '''
require('neogit').setup {}
'''

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'tani/dmacro.nvim'
lua_source = '''
require('dmacro').setup {
  dmacro_key = '<C-t>',
}
'''

