[[plugins]]
repo = 'https://github.com/neovim/nvim-lspconfig'
on_cmd = 'LspStart'
hook_add = '''
nnoremap <Space>ln <Cmd>LspStart<CR>
'''
hook_source = '''
source $MYVIMDIR/conf/plug/nvim/lspconfig.lua
'''
