[[plugins]]
repo = 'https://github.com/nvim-telescope/telescope.nvim'
on_cmd = 'Telescope'
on_lua = 'telescope'

[[plugins]]
repo = 'https://github.com/nvim-telescope/telescope-fzf-native.nvim'
on_source = 'telescope.nvim'
lua_source = '''
require('telescope').setup {
  extensions = {
    fzf = {
      fuzzy = true,
      override_generic_sorter = true,
      override_file_sorter = true,
      case_mode = 'smart_case',
    },
  },
}
require('telescope').load_extension('fzf')
'''

