[[plugins]]
repo = 'mattn/vim-molder'
lazy = 1
hook_add = '''
let g:loaded_netrw = 1
let g:loaded_netrwPlugin = 1
function s:init()
  if isdirectory(expand('%:p'))
    call dein#source('vim-molder')
    call molder#init()
    autocmd! vimrc_molder
  endif
endfunction
augroup vimrc_molder
  autocmd BufEnter * call s:init()
augroup END
'''
hook_source = '''
function! s:map_molder() abort
  nnoremap <buffer> <nowait> f <Cmd>call vimrc#fzf#ff#run()<CR>
  nmap <buffer> <silent> <nowait> h <plug>(molder-up)
  nmap <buffer> <silent> <nowait> l <plug>(molder-open)
endfunction

autocmd FileType molder call s:map_molder()

let g:molder_show_hidden = 1
'''

[[plugins]]
repo = 'mattn/vim-notification'
on_lua = 'vimrc.feat.notify'
lua_source = '''
require('vimrc.feat.notify').subscribe(function(msg)
  vim.call('notification#show', msg)
end)
'''
