[[plugins]]
repo = 'mattn/vim-molder'
hook_add = '''
function! s:map_molder() abort
  nnoremap <buffer> <nowait> f <Cmd>call vimrc#fzf#ff#run()<CR>
  nmap <buffer> <silent> <nowait> h <plug>(molder-up)
  nmap <buffer> <silent> <nowait> l <plug>(molder-open)
endfunction

autocmd FileType molder call s:map_molder()

let g:molder_show_hidden = 1
'''

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
