#!/bin/bash -u

cd $(dirname $0) || exit 1

if [[ -f "profiles/$1" ]]; then
  echo -n "上書きしてもおk?(y/N)"
  read ANSWER
  if [[ ! "${ANSWER}" = "y" ]]; then
    exit 1
  fi
fi
rsync -ac --mkpath --delete-before ~/.vim/ "profiles/$1/"
cd "profiles/$1"
git fetch local
if [[ -e "local/profiles/$1" ]]; then
  "local/profiles/$1"
fi
