[[plugins]]
repo = 'ayu-theme/ayu-vim'

[[plugins]]
repo = "NLKNguyen/papercolor-theme"

[[plugins]]
repo = 'bluz71/vim-nightfly-guicolors'

[[plugins]]
repo = 'catppuccin/nvim'
name = 'catppuccin'
lua_source = '''
-- require('catppuccin').setup {
--   integrations = {
--     fern = true,
--     ts_rainbow = true,
--   },
-- }
'''

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'cormacrelf/vim-colors-github'

[[plugins]]
repo = 'EdenEast/nightfox.nvim'

[[plugins]]
repo = 'ghifarit53/tokyonight-vim'

[[plugins]]
repo = 'habamax/vim-gruvbit'

[[plugins]]
repo = 'haishanh/night-owl.vim'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'kjssad/quantum.vim'

[[plugins]]
description = '''
Original: romgrk/github-light.vim
hi clearをしていない&pumblendを汚染する&Neovimでしか動かないのでfork
'''
repo = 'kuuote/github-light.vim'

[[plugins]]
repo = 'lifepillar/vim-solarized8'

[[plugins]]
repo = 'Rigellute/rigel'

[[plugins]]
repo = 'sainnhe/edge'

[[plugins]]
repo = 'sainnhe/everforest'

[[plugins]]
repo = 'sainnhe/gruvbox-material'

[[plugins]]
repo = 'sainnhe/sonokai'

[[plugins]]
repo = 'savq/melange'

[[plugins]]
repo = 'severij/vadelma'

[[plugins]]
repo = 'yasukotelin/shirotelin'

[[plugins]]
repo = 'yuttie/hydrangea-vim'

