[[plugins]]
repo = 'ayu-theme/ayu-vim'

[[plugins]]
repo = 'bluz71/vim-nightfly-guicolors'

[[plugins]]
repo = 'catppuccin/nvim'
name = 'catppuccin'
lazy = 1
lua_add = '''
require('vimrc.compat.autocmd').define('ColorSchemePre', {
  pattern = 'catppuccin*',
  callback = function()
    vim.call('dein#source', 'catppuccin')
    require('catppuccin').setup {
      integrations = {
        fern = true,
        notify = true,
        ts_rainbow = true,
      },
      term_colors = true,
    }
  end,
})
'''

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'cormacrelf/vim-colors-github'

[[plugins]]
repo = 'dracula/vim'
name = 'dracula'
lazy = 1
hook_add = '''
autocmd ColorSchemePre dracula ++once call dein#source('dracula')
'''

[[plugins]]
repo = 'EdenEast/nightfox.nvim'

[[plugins]]
repo = 'ghifarit53/tokyonight-vim'

[[plugins]]
repo = 'habamax/vim-gruvbit'

[[plugins]]
repo = 'haishanh/night-owl.vim'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'kjssad/quantum.vim'

[[plugins]]
description = '''
Original: romgrk/github-light.vim
hi clearをしていない&pumblendを汚染する&Neovimでしか動かないのでfork
'''
repo = 'kuuote/github-light.vim'

[[plugins]]
repo = 'lifepillar/vim-solarized8'

[[plugins]]
repo = 'Rigellute/rigel'

[[plugins]]
repo = 'sainnhe/edge'

[[plugins]]
repo = 'sainnhe/everforest'

[[plugins]]
repo = 'sainnhe/gruvbox-material'

[[plugins]]
repo = 'sainnhe/sonokai'

[[plugins]]
repo = 'savq/melange'

[[plugins]]
repo = 'severij/vadelma'

[[plugins]]
repo = 'yasukotelin/shirotelin'

[[plugins]]
repo = 'yuttie/hydrangea-vim'

[[plugins]]
repo = "NLKNguyen/papercolor-theme"

