[[plugins]]
repo = 'LumaKernel/ddc-file'

[[plugins]]
repo = 'Shougo/ddc-around'

[[plugins]]
repo = 'Shougo/ddc-cmdline'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'

[[plugins]]
repo = 'Shougo/ddc.vim'
hook_source = '''
let g:vimrc#ddc_sources = ['file', 'around', 'buffer']
" insert space for paragraph selector
" vip => :!jq -S .
let s:config_json =<< UNKO

{
  "backspaceCompletion": true,
  "completionMenu": "pum.vim",
  "sourceOptions": {
    "_": {
      "converters": [
        "converter_fuzzy"
      ],
      "ignoreCase": true,
      "matchers": [
        "matcher_fuzzy"
      ],
      "sorters": [
        "sorter_fuzzy"
      ]
    },
    "around": {
      "mark": "A"
    },
    "buffer": {
      "mark": "B"
    },
    "file": {
      "forceCompletionPattern": "\\S/\\S*",
      "isVolatile": true,
      "mark": "F",
      "minAutoCompleteLength": 1000
    },
    "necovim": {
      "mark": "V"
    },
    "nvim-lsp": {
      "forceCompletionPattern": "\\.\\w*|:\\w*|->\\w*",
      "mark": "lsp",
      "minAutoCompleteLength": 1
    }
  }
}

UNKO
let s:config = s:config_json->join('')->json_decode()
let s:config['sources'] = g:vimrc#ddc_sources
call ddc#custom#patch_global(s:config)
unlet s:config
unlet s:config_json
autocmd VimEnter * doautocmd <nomodeline> User vimrc-ddc
autocmd VimEnter * call ddc#enable()
'''

[[plugins]]
repo = 'Shougo/neco-vim'
hook_source = '''
function! s:setup_necovim() abort
  call ddc#custom#patch_filetype(['vim', 'toml'], 'sources', ['necovim'] + g:vimrc#ddc_sources)
endfunction
autocmd User vimrc-ddc call s:setup_necovim()
'''

[[plugins]]
repo = 'Shougo/pum.vim'
hook_add = '''
inoremap <Tab>   <Cmd>call pum#map#insert_relative(+1)<CR>
inoremap <S-Tab> <Cmd>call pum#map#insert_relative(-1)<CR>
inoremap <C-n>   <Cmd>call pum#map#insert_relative(+1)<CR>
inoremap <C-p>   <Cmd>call pum#map#insert_relative(-1)<CR>
inoremap <C-y>   <Cmd>call pum#map#confirm()<CR>
inoremap <C-e>   <Cmd>call pum#map#cancel()<CR>
'''

[[plugins]]
repo = 'matsui54/ddc-buffer'

[[plugins]]
repo = 'takker99/ddc-bitap'

[[plugins]]
repo = 'tani/ddc-fuzzy'
