[[plugins]]
repo = '4513echo/ddu-source-source'
lua_add = '''
local c = require('vimrc.command').define
c('DduSourceSource', function()
  require('ddu').start { 'source' }
end)
'''

[[plugins]]
repo = 'kuuote/ddu-filter-fuse'

[[plugins]]
repo = 'kuuote/ddu-source-mr'
lua_add = '''
local m = require('vimrc.map').define

for _, t in ipairs { 'mru', 'mrw', 'mrr' } do
  m('n', t, function()
    require('ddu').start {
      { name = 'mr', params = { kind = t } },
      name = 'file',
    }
  end)
end
'''

[[plugins]]
repo = 'matsui54/ddu-source-dein_update'
lua_add = '''
local c = require('vimrc.command').define
c('DduDeinUpdate', function()
  require('ddu').start { 'dein_update', name = 'dein_update' }
end)
'''

[[plugins]]
repo = 'matsui54/ddu-source-help'
lua_add = '''
require('vimrc.map').define('n', '<Space>fh', function()
  require('ddu').start { 'help' }
end)
'''

[[plugins]]
repo = 'Shougo/ddu-kind-file'

[[plugins]]
repo = 'Shougo/ddu-kind-word'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
lua_add = '''
require('vimrc.map').define('n', '<C-p>', function()
  require('ddu').start {
    {
      name = 'file_rec',
      options = { path = require('vimrc.util').find_root() },
    },
  }
end)
'''

[[plugins]]
repo = 'Shougo/ddu-source-file'

[[plugins]]
repo = 'Shougo/ddu-source-line'
lua_add = '''
require('vimrc.map').define('n', '<Space>fl', function()
  require('ddu').start { 'line' }
end)
'''

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
lua_add = '''
local au = require('vimrc.autocmd').define
local aug = require('vimrc.autocmd').group
local cmd = vim.cmd or vim.command
local fn = require('vimrc.convert').fn
local isnvim = vim.fn.has('nvim') == 1
local m = require('vimrc.map').define
local part = require('kutil.function').partition_keyvalue

local do_action = fn['ddu#ui#ff#do_action']

local function action(name)
  return function()
    do_action(name)
  end
end

local function item_action(tbl)
  local args, params = part(tbl)
  params[vim.type_idx] = vim.types.dictionary
  local farg = {
    name = args[1],
    params = params,
  }
  return function()
    do_action('itemAction', farg)
  end
end

au('FileType', {
  pattern = 'ddu-ff',
  callback = function()
    local opts = {
      buffer = true,
      nowait = true,
    }
    m('n', '<CR>', action('itemAction'), opts)
    m('n', '<Space>', action('toggleSelectItem'), opts)
    m('n', 'i', action('openFilterWindow'), opts)
    m('n', 'p', action('preview'), opts)
    m('n', 'q', action('quit'), opts)
    if vim.b.ddu_ui_name == 'file' then
      m('n', 't', item_action { 'open', command = 'tabedit' }, opts)
      m('n', 's', item_action { 'open', command = 'split' }, opts)
      m('n', 'v', item_action { 'open', command = 'vsplit' }, opts)
      m('n', '<C-q>', function()
        do_action('clearSelectAllItems')
        do_action('toggleAllItems')
        item_action { 'quickfix' }()
      end, opts)
    end
    if isnvim then
      m('n', 'P', function()
        local preview = action('preview')
        local bufnr = vim.api.nvim_get_current_buf()
        local group = 'ddu-ui-auto_action' -- ddu-ui-ffが内部で使っているグループ名
        aug(group, {})
        au('CursorMoved', {
          group = group,
          buffer = 0,
          callback = function()
            preview()
          end,
        })
      end, opts)
    end
  end,
})

au('FileType', {
  pattern = 'ddu-ff-filter',
  callback = function()
    local opts = {
      buffer = true,
      nowait = true,
    }
    m({ 'n', 'i' }, '<CR>', function()
      cmd('stopinsert')
      vim.call('ddu#ui#ff#close')
    end, opts)
    m('i', '<C-j>', function()
      vim.call('ddu#ui#ff#execute', [[call cursor(line('.')+1, 0)]])
      cmd('redraw!')
    end, opts)
    m('i', '<C-k>', function()
      vim.call('ddu#ui#ff#execute', [[call cursor(line('.')-1, 0)]])
      cmd('redraw!')
    end, opts)
    -- for fzf and jis keyboard
    m('i', ':', [[']], { buffer = true })
    -- 'のルール追加するくらいならlexima無効化する
    vim.b.lexima_disabled = true
  end,
})
'''

[[plugins]]
repo = 'Shougo/ddu.vim'
on_func = 'ddu#'
hook_source = '''
source ~/.vim/conf/plug/ddu.vim
'''

[[plugins]]
repo = 'shun/ddu-rg'
lua_add = '''
local c = require('vimrc.command').define
c('DduRgLive', function()
  require('ddu').start {
    {
      name = 'rg',
      options = {
        matchers = {},
      },
      params = {
        path = require('vimrc.util').find_root(),
      },
    },
    name = 'file',
    uiParams = {
      ff = {
        ignoreEmpty = false,
        autoResize = false,
      },
    },
    volatile = true,
  }
end)
'''

[[plugins]]
repo = 'yuki-yano/ddu-filter-fzf'

