[[plugins]]
repo = 'Shougo/ddu-kind-file'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'

[[plugins]]
repo = 'Shougo/ddu-source-line'

[[plugins]]
repo = 'Shougo/ddu-ui-std'
hook_add = '''
" copy from doc
autocmd FileType ddu-std call s:ddu_my_settings()
function! s:ddu_my_settings() abort
  nnoremap <buffer><silent> <CR>
  \ <Cmd>call ddu#ui#std#do_action('itemAction')<CR>
  nnoremap <buffer><silent> <Space>
  \ <Cmd>call ddu#ui#std#do_action('toggleSelectItem')<CR>
  nnoremap <buffer><silent> i
  \ <Cmd>call ddu#ui#std#do_action('openFilterWindow')<CR>
  nnoremap <buffer><silent> q
  \ <Cmd>call ddu#ui#std#do_action('quit')<CR>
endfunction

autocmd FileType ddu-std-filter call s:ddu_filter_my_settings()
function! s:ddu_filter_my_settings() abort
  inoremap <buffer><silent> <CR>
  \ <Esc><Cmd>close<CR>
  nnoremap <buffer><silent> <CR>
  \ <Cmd>close<CR>
endfunction
'''

[[plugins]]
repo = 'Shougo/ddu.vim'
hook_source = '''
call ddu#custom#patch_global('ui', 'std')

" Specify matcher.
call ddu#custom#patch_global({
    \   'sourceOptions': {
    \     '_': {
    \       'matchers': ['matcher_fzf'],
    \     },
    \   },
    \   'uiParams': {
    \     'std': {
    \       'split': 'floating',
    \     },
    \   },
    \ })
'''

[[plugins]]
repo = 'kuuote/ddu-source-mr'

[[plugins]]
repo = 'yuki-yano/ddu-filter-fzf'
