[[plugins]]
repo = 'Shougo/ddu-kind-file'

[[plugins]]
repo = 'Shougo/ddu-kind-word'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'

[[plugins]]
repo = 'Shougo/ddu-source-line'

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
hook_add = '''
autocmd FileType ddu-ff call s:ddu_ff_common_mapping()
function! s:ddu_ff_common_mapping() abort
  " copy from doc
  nnoremap <buffer> <nowait> <CR>
  \ <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
  nnoremap <buffer> <nowait> <Space>
  \ <Cmd>call ddu#ui#ff#do_action('toggleSelectItem')<CR>
  nnoremap <buffer> <nowait> i
  \ <Cmd>call ddu#ui#ff#do_action('openFilterWindow')<CR>
  nnoremap <buffer> <nowait> q
  \ <Cmd>call ddu#ui#ff#do_action('quit')<CR>
endfunction

autocmd BufEnter ddu-ff-file call s:ddu_ff_file_mapping()
function! s:ddu_ff_file_mapping() abort
  nnoremap <buffer> <nowait> t
  \ <Cmd>call ddu#ui#ff#do_action('itemAction', {'action': 'open', 'params': {'command': 'tabedit'}})<CR>
endfunction

autocmd FileType ddu-ff-filter call s:ddu_filter_my_settings()
function! s:ddu_filter_my_settings() abort
  inoremap <buffer><silent> <CR>
  \ <Esc><Cmd>close<CR>
  nnoremap <buffer><silent> <CR>
  \ <Cmd>close<CR>
endfunction
'''

[[plugins]]
repo = 'Shougo/ddu.vim'
hook_source = '''
call ddu#custom#patch_global({
\   'kindOptions': {
\     'command': {
\       'defaultAction': 'execute',
\     },
\     'file': {
\       'defaultAction': 'open',
\     },
\     'word': {
\       'defaultAction': 'append',
\     },
\   },
\   'sourceOptions': {
\     '_': {
\       'ignoreCase': v:true,
\       'matchers': ['matcher_fuse'],
\     },
\     'command': {
\       'matchers': ['matcher_fuse'],
\     },
\   },
\   'ui': 'ff',
\   'uiParams': {
\     'ff': {
\       'split': has('nvim') ? 'floating' : 'horizontal',
\       'startFilter': v:true,
\     },
\   },
\ })
'''

[[plugins]]
repo = 'kuuote/ddu-filter-fuse'

[[plugins]]
repo = 'kuuote/ddu-source-mr'
hook_add = '''
nnoremap mru <Cmd>call ddu#start({'name': 'file', 'sources': [{'name': 'mr'}]})<CR>
nnoremap mrw <Cmd>call ddu#start({'name': 'file', 'sources': [{'name': 'mr', 'params': {'kind': 'mrw'}}]})<CR>
nnoremap mrr <Cmd>call ddu#start({'name': 'file', 'sources': [{'name': 'mr', 'params': {'kind': 'mrr'}}]})<CR>
'''

[[plugins]]
repo = 'yuki-yano/ddu-filter-fzf'
