[[plugins]]
repo = '4513ECHO/ddu-source-colorscheme'

[[plugins]]
repo = '4513ECHO/ddu-source-source'
lua_add = '''
local c = require('vimrc.command').define
c('DduSourceSource', function()
  require('ddu').start { 'source' }
end)
'''

[[plugins]]
repo = 'kuuote/ddu-filter-fuse'

[[plugins]]
repo = 'kuuote/ddu-source-git_diff'

[[plugins]]
repo = 'kuuote/ddu-source-mr'
lua_add = '''
local m = require('vimrc.compat.map').define

-- ある意味覚えやすくていいマッピング
for _, t in ipairs { 'mru', 'mrw', 'mrr' } do
  m('n', t, function()
    require('ddu').start {
      { name = 'mr', params = { kind = t } },
      name = 'file',
    }
  end)
end
'''

[[plugins]]
repo = 'kuuote/ddu-vim-ui-select'
if = '!has("nvim") || g:vim_ui_select ==# "ddu.vim"'
rev = 'vim_compat'

[[plugins]]
repo = 'matsui54/ddu-source-dein_update'
lua_add = '''
local c = require('vimrc.command').define
c('DduDeinUpdate', function()
  require('ddu').start { 'dein_update', name = 'dein_update' }
end)
'''

[[plugins]]
repo = 'matsui54/ddu-source-help'
lua_add = '''
require('vimrc.compat.map').define('n', '<Space>fh', function()
  require('ddu').start { 'help' }
end)
'''

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'

[[plugins]]
repo = 'Shougo/ddu-filter-sorter_alpha'

[[plugins]]
repo = 'Shougo/ddu-kind-file'

[[plugins]]
repo = 'Shougo/ddu-kind-word'

[[plugins]]
repo = 'Shougo/ddu-source-action'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
lua_add = '''
require('vimrc.compat.map').define('n', '<C-p>', function()
  require('ddu').start {
    {
      name = 'file_rec',
      options = {
        path = require('vimrc.util').find_root(),
        sorters = { 'sorter_alpha_path', 'sorter_distance' },
      },
    },
    name = 'file',
  }
end)
'''

[[plugins]]
repo = 'Shougo/ddu-source-file'

[[plugins]]
repo = 'Shougo/ddu-source-line'
lua_add = '''
require('vimrc.compat.map').define('n', '<Space>fl', function()
  require('ddu').start { 'line' }
end)
'''

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
hook_add = '''
autocmd FileType ddu-ff ++once ++nested luafile $DOTVIM/conf/plug/ddu_ui_ff.lua
'''

[[plugins]]
repo = 'Shougo/ddu.vim'
hook_source = '''
source $DOTVIM/conf/plug/ddu.vim
luafile $DOTVIM/conf/plug/ddu.lua
'''

[[plugins]]
repo = 'shun/ddu-source-rg'
on_cmd = 'DduRgLive'
lua_source = '''
local vimcall = require('vimrc.compat.convert').call

require('vimrc.plug.ddu_ui_ff').setup_table['rg'] = function()
  require('vimrc.compat.map').define('n', 'm', function()
    require('vimrc.menu').which {
      info = 'change sorter',
      items = {
        m = {
          info = 'mtime order',
          fn = function()
            vimcall('ddu#ui#ff#do_action', 'updateOptions', {
              sourceOptions = {
                rg = {
                  sorters = { 'sorter_alpha_path', 'sorter_mtime' },
                },
              },
            })
          end,
        },
      },
    }
  end, {
    desc = 'ddu-source-rg:menu',
    buffer = true,
    nowait = true,
  })
end

require('artemis').create_command('DduRgLive', function(a)
  local root
  if a.args:match('current') then
    root = vim.fn.expand('%:p:h')
  else
    root = require('vimrc.util').find_root()
  end
  require('ddu').start {
    'rg',
    name = 'file:rg',
    sourceOptions = {
      rg = {
        converters = {},
        matchers = {},
        sorters = { 'sorter_alpha_path' },
        path = root,
        volatile = true,
      },
    },
    uiParams = {
      ff = {
        ignoreEmpty = false,
        autoResize = false,
      },
    },
  }
end, {
  nargs = '*',
})
'''

[[plugins]]
repo = 'uga-rosa/ddu-source-lsp'

[[plugins]]
repo = 'yuki-yano/ddu-filter-fzf'

