[[plugins]]
comment = '本体に入ったので'
repo = 'cespare/vim-toml'
hook_add = '''
function! s:dein_toml_syntax() abort
  if expand('%:p') =~# '\vconf/[^/]+.toml$'
    call dein#toml#syntax()
  endif
endfunction
autocmd FileType toml ++nested call timer_start(0, {id->s:dein_toml_syntax()})
'''

[[plugins]]
comment = '''
ddu-source-mr使ってるので
'''
repo = 'lambdalisue/mr-quickfix.vim'

[[__plugins__]]
comment = '''
いまいち合わなかった
特定の位置に飛びたいケースがそんなにない
  あまり管理したくない
もっといい単位があるかもしれないので考えていきたい
'''
repo = 'MattesGroeger/vim-bookmarks'
hook_add = '''
let g:bookmark_no_default_key_mappings = 1
nmap mm <Plug>BookmarkToggle
nmap mx <Plug>BookmarkClearAll
nmap mf <Cmd>FzfPreviewBookmarksRpc<CR>

let g:bookmark_save_per_working_dir = 1
call mkdir('/tmp/bookmarks', 'p')
function! BMWorkDirFileLocation() abort
  let root = system('git rev-parse --show-toplevel')
  if v:shell_error
    let root = getcwd()
  endif
  let root = substitute(root, '/', '@', 'g')
  return '/tmp/bookmarks/' .. root
endfunction
'''

[[plugins]]
comment = '''
ddudeinupdateを使うようになったので
'''
repo = 'wsdjeg/dein-ui.vim'
hook_add = '''
autocmd FileType SpaceVimPlugManager autocmd TextChanged <buffer> normal! G
'''

