[[plugins]]
repo = 'kuuote/lspoints'
on_ft = [
  'lua',
  'typescript',
  'typescriptreact',
]
hook_source = '''
source $DOTVIM/conf/plug/lspoints.vim
'''
lua_source = '''
local vimx = require('artemis')
vimx.create_autocmd('FileType', {
  pattern = { 'lua' },
  callback = function()
    require('vimrc.plug.lspoints').server.luals.attach()
  end,
})
vimx.create_autocmd('FileType', {
  pattern = { 'typescript', 'typescriptreact' },
  callback = function()
    require('vimrc.plug.lspoints').server.denols.attach()
  end,
})
'''

