[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
" さすまつ https://mattn.kaoriya.net/software/vim/20191231213507.htm

function! s:on_lsp_buffer_enabled() abort
  setlocal omnifunc=lsp#complete
  setlocal signcolumn=yes
  nmap <buffer> gd <Plug>(lsp-definition)
  nmap <buffer> K <Plug>(lsp-hover)
  nnoremap <buffer> <LocalLeader>la <Cmd>LspCodeActionSync<CR>
  nnoremap <buffer> <LocalLeader>lf <Cmd>LspDocumentFormatSync<CR>
endfunction

augroup vimrc
  autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END

let g:lsp_diagnostics_enabled = 1
let g:lsp_diagnostics_echo_cursor = 1
let g:asyncomplete_auto_popup = 1
let g:asyncomplete_auto_completeopt = 1
let g:asyncomplete_popup_delay = 200
let g:lsp_text_edit_enabled = 1

command! LspDebug let lsp_log_verbose=1 | let lsp_log_file = expand('~/lsp.log')
'''

[[plugins]]
repo = 'shun/ddc-vim-lsp'
hook_add = '''
let g:vimrc#ddc_source_options['vim-lsp'] = {'forceCompletionPattern': '\.', 'minAutoCompleteLength': 1}

function! s:setup_ddc_vim_lsp() abort
  let sources = ['vim-lsp'] + g:vimrc#ddc_sources_sorted
  call ddc#custom#patch_filetype([
  \ 'go',
  \ 'rust',
  \ 'typescript',
  \ 'typescriptreact',
  \ ], 'sources', sources)
endfunction
autocmd User vimrc-ddc call s:setup_ddc_vim_lsp()
'''
