[[plugins]]
repo = 'hrsh7th/nvim-kit'

[[plugins]]
repo = 'lewis6991/impatient.nvim'

[[plugins]]
repo = 'monaqa/dial.nvim'
on_map = {"n" = "<Plug>(dial"}
hook_add = '''
" from help
nnoremap <C-a> <Plug>(dial-increment)
nnoremap <C-x> <Plug>(dial-decrement)
xnoremap <C-a> <Plug>(dial-increment)
xnoremap <C-x> <Plug>(dial-decrement)
xnoremap g<C-a> <Plug>(dial-increment-additional)
xnoremap g<C-x> <Plug>(dial-decrement-additional)
'''
lua_source = '''
local augend = require('dial.augend')
require('dial.config').augends:register_group {
  -- グループ名を指定しない場合に用いられる被加数
  default = {
    augend.integer.alias.decimal, -- nonnegative decimal number
    augend.integer.alias.hex, -- nonnegative hex number
    augend.constant.alias.bool,
    -- date (2022/02/19, etc.)
    augend.date.new {
      pattern = '%Y/%m/%d',
      default_kind = 'day',
    },
  },
}
'''

[[plugins]]
repo = 'MunifTanjim/nui.nvim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'
on_lua = 'plenary'

[[plugins]]
repo = 'nvim-lua/popup.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
on_cmd = 'Telescope'
on_lua = 'telescope'

[[plugins]]
repo = 'rcarriga/nvim-notify'

[[plugins]]
repo = 'Shougo/deol.nvim'
on_cmd = 'Deol'
hook_add = '''
command! DeolCurrent execute printf('Deol -cwd=%s', isdirectory(expand('%')) ? expand('%') : getftype(expand('%')) == 'file' ? expand('%:h') : getcwd())
'''
hook_source = '''
call ddc#custom#patch_filetype(['deol', 'zsh'], 'specialBufferCompletion', v:true)
call ddc#custom#patch_filetype('deol', 'sources', ['zsh', 'shell-history', 'around'])
" auto cdはEditバッファのみ有効なのでfileはこちら
call ddc#custom#patch_filetype('zsh', 'sources', ['file', 'zsh', 'shell-history'])

autocmd FileType deol tnoremap <buffer> <C-e> <C-\><C-N>G<Cmd>DeolEdit<CR><C-u><Cmd>call feedkeys("cd .\<lt>CR>")<CR>

function! s:deol_ft_zsh() abort
  nnoremap <buffer> <C-e> <Esc><Cmd>close<CR>i
  inoremap <buffer> <C-e> <Esc><Cmd>close<CR>i
endfunction

autocmd FileType zsh if bufname() =~# '^deol-edit' | call s:deol_ft_zsh() | endif
'''

[[plugins]]
repo = 'skanehira/jumpcursor.vim'
on_map = '<Plug>'
hook_add = '''
nmap [j <Plug>(jumpcursor-jump)
'''

[[plugins]]
repo = 'stevearc/dressing.nvim'
lazy = 1
lua_add = '''
if vim.g.vim_ui_select:match('^dressing_') then
  vim.ui.select = function(...)
    vim.call('dein#source', 'dressing.nvim')
    return vim.ui.select(...)
  end
end
'''
lua_source = '''
require('dressing').setup {
  select = {
    enabled = true,
    backend = { 'telescope' }
  }
}
'''

[[plugins]]
repo = 'tamago324/lir.nvim'
on_lua = 'lir'
lua_add = '''
local autocmd = require('vimrc.compat.autocmd')
local group = 'vimrc#lir'
autocmd.group(group, {})
autocmd.define('BufEnter', {
  group = group,
  callback = function()
    if vim.fn.isdirectory(vim.fn.expand('%:p')) == 1 then
      autocmd.group(group, {})
      require('lir').init()
    end
  end
})
'''
lua_source = '''
    local lir = require('lir')
    local actions = require('lir.actions')

    lir.setup {
      show_hidden_files = true,
      mappings = {
        ['f'] = function()
          vim.call('vimrc#fzf#ff#run')
        end,
        ['l'] = actions.edit,
        ['<C-s>'] = actions.split,
        ['<C-v>'] = actions.vsplit,
        ['<C-t>'] = actions.tabedit,

        ['h'] = actions.up,
        ['q'] = actions.quit,

        ['K'] = actions.mkdir,
        ['N'] = actions.newfile,
        ['R'] = actions.rename,
        ['@'] = actions.cd,
        ['Y'] = actions.yank_path,
        ['.'] = actions.toggle_show_hidden,
      },
    }
'''

[[plugins]]
repo = 'uga-rosa/ccc.nvim'
on_cmd = 'CccHighlighterEnable'
lua_source = '''
local ccc = require('ccc')

ccc.setup {
  pickers = {
    ccc.picker.hex,
    ccc.picker.css_rgb,
    ccc.picker.css_hsl,
    ccc.picker.css_hwb,
    ccc.picker.css_lab,
    ccc.picker.css_lch,
    ccc.picker.css_oklab,
    ccc.picker.css_oklch,
  },
}
'''

[[plugins]]
repo = 'vim-skk/eskk.vim'
on_func = 'eskk#enable'
lua_add = '''
vim.call('hypermap#map', 'zj', 'eskk#enable()', { eval = true })
'''
lua_source = '''
-- use dotfiles dictionary
vim.g['eskk#dictionary'] = { path = vim.env.HOME .. '/.vim/tmp/.skk-jisyo' }
vim.g['eskk#large_dictionary'] = {
  path = vim.env.HOME .. '/.vim/tmp/.skk-jisyo',
  sorted = true,
  encoding = 'euc-jp',
}

-- improve eskk enabler
-- see https://thinca.hatenablog.com/entry/20120716/1342374586
-- inoremap <expr> <script> f getline('.')[col('.') - 2] ==# 'j' ? "\<BS>" .. eskk#enable() : 'f'
vim.call('hypermap#map', 'zj', 'eskk#enable()', { eval = true })

vim.api.nvim_create_autocmd('User', {
  pattern = 'eskk-enable-post',
  callback = function()
    vim.keymap.set('l', 'l', '<Plug>(eskk:disable)', {
      buffer = vim.fn.bufnr(),
    })
  end,
})
'''
hook_add = '''
"register alphabet table
function! s:eskk_initialize_pre()
  let t = eskk#table#new('rom_to_hira*', 'rom_to_hira')
  call t.add_map('z ', '　')
  call eskk#register_mode_table('hira', t)
endfunction

augroup vimrc
  autocmd User eskk-initialize-pre call s:eskk_initialize_pre()
augroup END
'''

[[plugins]]
repo = 'yuki-yano/tsnip.nvim'
lua_add = '''
-- vim.g.tsnip_use_nui = false
'''

