[[plugins]]
repo = 'gamoutatsumi/ddu-source-nvim-lsp'

[[plugins]]
repo = 'j-hui/fidget.nvim'
on_event = 'LspAttach'
lua_source = '''
require('fidget').setup {
  text = {
    spinner = 'moon', -- 月が綺麗ですね
  },
}
'''

[[plugins]]
repo = 'matsui54/denops-signature_help'
on_source = 'nvim-lspconfig'
hook_source = '''
let g:signature_help_config = {
\   'style': 'virtual',
\ }
call signature_help#enable()
'''

[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_ft = ['lua', 'typescript', 'typescriptreact', 'rust']
lua_source = '''
local c = require('cmp_nvim_lsp').default_capabilities()
vim.api.nvim_create_autocmd('LspAttach', {
  callback = function()
    local opts = {
      buffer = true,
      noremap = true,
      silent = true,
    }
    vim.keymap.set('n', 'gd', '<cmd>lua vim.lsp.buf.definition()<CR>', opts)
    vim.keymap.set('n', 'K', '<cmd>lua vim.lsp.buf.hover()<CR>', opts)
    vim.keymap.set('n', 'ma', '<Cmd>lua vim.lsp.buf.code_action()<CR>', opts)
    vim.keymap.set('n', 'mf', '<cmd>lua vim.lsp.buf.format()<CR>', opts)
    vim.keymap.set('n', 'mS', function()
      vim.lsp.stop_client(vim.lsp.get_active_clients())
    end, opts)
  end,
})

local lsp = require('lspconfig')

lsp.sumneko_lua.setup {
  capabilites = c,
  settings = {
    Lua = {
      runtime = {
        version = 'LuaJIT',
        path = {
          'lua/?.lua',
          'lua/?/init.lua',
        },
      },
      completion = {
        callSnippet = 'Replace',
      },
      diagnostics = {
        globals = { 'vim' },
      },
      telemetry = {
        enable = false,
      },
    },
  },
}

lsp.rust_analyzer.setup {}

lsp.denols.setup {
  init_options = {
    lint = true,
    unstable = true,
  },
}

'''

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'
on_if = 'dein#is_available("ddc.vim")'
lua_add = '''
vim.api.nvim_create_autocmd('User', {
  pattern = 'vimrc-ddc',
  callback = function()
    local e = vim.list_extend
    local sources = e(e(vim.g['vimrc#ddc_sources_front'], {'nvim-lsp'}), vim.g['vimrc#ddc_sources'])
    vim.call('ddc#custom#patch_filetype', {
      'lua',
      'rust',
      'typescript',
      'typescriptreact',
    }, 'sources', sources)
  end,
})
'''

