[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = 0
hook_source = '''
lua <<EOF
require'nvim-treesitter.configs'.setup {
  highlight = {
    enable = true,
  },
}
EOF
lua <<EOF
local parser_config = require "nvim-treesitter.parsers".get_parser_configs()
parser_config.typescript.used_by = "typescriptreact"
EOF
'''

[[plugins]]
repo = 'p00f/nvim-ts-rainbow'
hook_source = '''
lua <<unko
require'nvim-treesitter.configs'.setup {
  rainbow = {
    enable = true,
  },
}
unko
'''
