[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = 0
hook_source = '''
lua <<unko
require'nvim-treesitter.configs'.setup {
  highlight = {
    enable = true,
  },
}
unko
lua <<unko
require('nvim-treesitter.utils').get_parser_install_dir = function(folder_name)
  local path = table.concat({'/data/vim/treesitter', folder_name or 'parser'}, '/')
  pcall(vim.fn.mkdir, path, 'p')
  return path
end
vim.o.runtimepath = vim.o.runtimepath .. ',/data/vim/treesitter'
unko
'''

[[plugins]]
repo = 'p00f/nvim-ts-rainbow'
hook_source = '''
lua <<unko
require'nvim-treesitter.configs'.setup {
  rainbow = {
    enable = true,
  },
}
unko
'''
