[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
on_cmd = 'TSUpdate'
on_event = 'BufRead'
lua_source = '''
require('nvim-treesitter.configs').setup({
  highlight = {
    enable = true,
    disable = {'help'},
  },
  parser_install_dir = '/data/vim/treesitter'
})
vim.o.runtimepath = vim.o.runtimepath .. ',/data/vim/treesitter'
'''

[[plugins]]
repo = 'p00f/nvim-ts-rainbow'
on_source = 'nvim-treesitter'
hook_source = '''
lua <<unko
require'nvim-treesitter.configs'.setup {
  rainbow = {
    enable = true,
  },
}
unko
'''

