#!/bin/bash -u

ROOT=${ROOT:-/data/vim}

deno run -A --import-map=import_map.json main.ts -r $ROOT -v ~/.vim/load_vim.vim assemble vim "$@"
deno run -A --import-map=import_map.json main.ts -r $ROOT -v ~/.vim/load_nvim.vim assemble nvim "$@"
