#!/bin/bash -u

jq -r '.[] | .path' ./out.json | while read path; do
(
  cd $path || exit 1

  [[ "$(git rev-parse @)" = "$(git rev-parse @{u})" ]] && exit

  echo $path
  for doc in $(ls -1 | grep '^\(doc\|README\)'); do
    git --no-pager diff -R @{u} $doc
  done

  [[ -e .vimrc_hash ]] && exit

  git merge --ff-only
  if [[ -e denops ]]; then
    deno --unstable cache --no-check denops/**/*.ts
  fi
)
done

touch ~/.vim/vimrc
