[[plugins]]
repo = 'https://github.com/catppuccin/nvim'
name = 'catppuccin'
lazy = true
hook_add = '''
autocmd vimrc ColorSchemePre catppuccin* call dpp#source(['catppuccin'])
'''
lua_source = '''
require('catppuccin').setup {
  integrations = {
    notify = true,
  },
  term_colors = true,
}
'''

[[plugins]]
repo = 'https://github.com/EdenEast/nightfox.nvim'

[[plugins]]
repo = 'https://github.com/eihigh/vim-aomi-grayscale'

[[plugins]]
repo = 'https://github.com/kyoh86/momiji'

[[plugins]]
repo = 'https://github.com/mcchrish/zenbones.nvim'

[[plugins]]
repo = 'https://github.com/sainnhe/edge'

[[plugins]]
repo = 'https://github.com/yuttie/hydrangea-vim'

