[[plugins]]
repo = 'https://github.com/catppuccin/nvim'
name = 'catppuccin'
lazy = true
lua_source = '''
require('catppuccin').setup {
  integrations = {
    notify = true,
  },
  term_colors = true,
}
'''

[[plugins]]
repo = 'https://github.com/eihigh/vim-aomi-grayscale'

[[plugins]]
repo = 'https://github.com/sainnhe/edge'

[[plugins]]
repo = 'https://github.com/yuttie/hydrangea-vim'

