[[plugins]]
repo = 'LumaKernel/ddc-source-file'

[[plugins]]
repo = 'Shougo/ddc-source-around'

[[plugins]]
repo = 'Shougo/ddc-source-cmdline'

[[plugins]]
repo = 'Shougo/ddc-source-input'

[[plugins]]
repo = 'Shougo/ddc-source-line'

[[plugins]]
repo = 'Shougo/ddc-source-nvim-lsp'

[[plugins]]
repo = 'Shougo/ddc-source-shell-native'

[[plugins]]
repo = 'Shougo/ddc-ui-pum'

[[plugins]]
repo = 'Shougo/ddc.vim'
hook_add = '''
autocmd CmdlineEnter,InsertEnter * ++once source $VIMDIR/conf/plug/ddc.vim
'''

[[plugins]]
repo = 'Shougo/pum.vim'
# L<mappings-pum_vim>

[[plugins]]
repo = 'tani/ddc-fuzzy'

