[[plugins]]
repo = 'https://github.com/kuuote/ddc-source-yank'
hook_add = '''
nnoremap cd <Cmd>call ddc#source#yank#clear()<CR>
nnoremap cy <Cmd>set operatorfunc=ddc#source#yank#register<CR>g@
nnoremap cyy <Cmd>set operatorfunc=ddc#source#yank#register<CR>g@_
xnoremap Y <Cmd>set operatorfunc=ddc#source#yank#register<CR>g@
'''

[[plugins]]
repo = 'https://github.com/LumaKernel/ddc-source-file'

[[plugins]]
repo = 'https://github.com/Shougo/ddc-source-around'

[[plugins]]
repo = 'https://github.com/Shougo/ddc-source-cmdline'

[[plugins]]
repo = 'https://github.com/Shougo/ddc-source-input'

[[plugins]]
repo = 'https://github.com/Shougo/ddc-source-line'

[[plugins]]
repo = 'https://github.com/Shougo/ddc-source-lsp'

[[plugins]]
repo = 'https://github.com/Shougo/ddc-source-shell-native'

[[plugins]]
repo = 'https://github.com/Shougo/ddc-ui-native'

[[plugins]]
repo = 'https://github.com/Shougo/ddc-ui-none'

[[plugins]]
repo = 'https://github.com/Shougo/ddc-ui-pum'

[[plugins]]
repo = 'https://github.com/Shougo/ddc.vim'
hook_add = '''
autocmd vimrc CmdlineEnter,InsertEnter * ++once source $VIMDIR/conf/plug/ddc.vim
'''

[[plugins]]
repo = 'https://github.com/Shougo/pum.vim'
# L<mappings-pum_vim>

[[plugins]]
repo = 'https://github.com/tani/ddc-fuzzy'

