[[plugins]]
repo = 'https://github.com/kuuote/ddu-source-git_diff'

[[plugins]]
repo = 'https://github.com/kuuote/ddu-source-git_status'
# L<ddu-source-git_status>
hook_add = '''
nnoremap gs <Cmd>call ddu#start({'name':'git_status','sourceOptions':{'_': {'path': expand('%:p')}}})<CR>
'''

[[plugins]]
repo = 'https://github.com/kuuote/ddu-source-mr'
# L<ddu-local-mr>
hook_add = '''
nnoremap mru <Cmd>call ddu#start({'name':'mru'})<CR>
nnoremap mrw <Cmd>call ddu#start({'name':'mrw'})<CR>
nnoremap mrr <Cmd>call ddu#start({'name':'mrr'})<CR>
'''

[[plugins]]
repo = 'https://github.com/kyoh86/ddu-filter-converter_hl_dir'
# L<ddu-filter-converter_hl_dir>

[[plugins]]
repo = 'https://github.com/matsui54/ddu-source-file_external'
hook_add = '''
nnoremap ;rw <Cmd>Ddu -name=file_ext_mrw -source-option-_-path=`gin#util#worktree()`<CR>
nnoremap ;mrw <Cmd>Ddu -name=file_ext_mrw -source-option-_-path=`expand('%:p:h')`<CR>
'''

[[plugins]]
repo = 'https://github.com/matsui54/ddu-source-help'
# L<ddu-local-help>
hook_add = '''
nnoremap dh <Cmd>call denops#request('ddu', 'start', [{'name':'help'}])<CR>
'''

[[plugins]]
repo = 'https://github.com/Shougo/ddu-column-filename'

[[plugins]]
repo = 'https://github.com/Shougo/ddu-commands.vim'
on_cmd = ['Ddu']

[[plugins]]
repo = 'https://github.com/Shougo/ddu-filter-matcher_substring'

[[plugins]]
repo = 'https://github.com/Shougo/ddu-filter-sorter_alpha'

[[plugins]]
repo = 'https://github.com/Shougo/ddu-kind-file'
# L<ddu-kind-file>

[[plugins]]
repo = 'https://github.com/Shougo/ddu-source-file_rec'

[[plugins]]
repo = 'https://github.com/Shougo/ddu-source-file'

[[plugins]]
repo = 'https://github.com/Shougo/ddu-source-line'
# L<ddu-local-line>
hook_add = '''
nnoremap dl <Cmd>call denops#request('ddu', 'start', [{'name':'line'}])<CR>
'''

[[plugins]]
repo = 'https://github.com/Shougo/ddu-ui-ff'

[[plugins]]
repo = 'https://github.com/Shougo/ddu-ui-filer'

[[plugins]]
repo = 'https://github.com/Shougo/ddu.vim'
# L<ddu-global>
hook_add = '''
autocmd User DenopsReady source $VIMDIR/conf/plug/ddu.vim
'''

[[plugins]]
repo = 'https://github.com/shun/ddu-source-rg'
lazy = 1

[[plugins]]
repo = 'https://github.com/uga-rosa/ddu-source-lsp'
hook_add = '''
let g:ddu_source_lsp_clientName = 'lspoints'
'''

[[plugins]]
repo = 'https://github.com/yuki-yano/ddu-filter-fzf'
# L<ddu-filter-matcher_fzf>

