[[plugins]]
repo = 'https://github.com/kuuote/ddu-filter-converter_normalize_hl'

[[plugins]]
repo = 'https://github.com/kuuote/ddu-source-git_diff'

[[plugins]]
repo = 'https://github.com/kuuote/ddu-source-git_status'
# L<ddu-source-git_status>
hook_add = '''
nnoremap gs <Cmd>call ddu#start({'name':'git_status','sourceOptions':{'_': {'path': expand('%:p')}}})<CR>
'''

[[plugins]]
repo = 'https://github.com/kuuote/ddu-source-mr'
# L<ddu-local-mr>
hook_add = '''
nnoremap mru <Cmd>call ddu#start({'name':'mru'})<CR><Cmd>call vimrc#feat#ddu#ff#wait_start(v:false)<CR>
nnoremap mrw <Cmd>call ddu#start({'name':'mrw'})<CR><Cmd>call vimrc#feat#ddu#ff#wait_start(v:false)<CR>
nnoremap mrr <Cmd>call ddu#start({'name':'mrr'})<CR><Cmd>call vimrc#feat#ddu#ff#wait_start(v:false)<CR>
'''

[[plugins]]
repo = 'https://github.com/kuuote/ddu-source-tags'
# L<ddu-local-tags>
hook_add = '''
nnoremap ;t <Cmd>call ddu#start({'name':'tags'})<CR>
'''

[[plugins]]
repo = 'https://github.com/kyoh86/ddu-filter-converter_hl_dir'
# L<ddu-filter-converter_hl_dir>

[[plugins]]
repo = 'https://github.com/matsui54/ddu-source-file_external'
hook_add = '''
nnoremap ;rw <Cmd>Ddu -name=file_ext_mrw -source-option-_-path=`vimrc#git#find_root()`<CR><Cmd>call vimrc#feat#ddu#ff#wait_start(v:false)<CR>
nnoremap ;mrw <Cmd>Ddu -name=file_ext_mrw -source-option-_-path=`expand('%:p:h')`<CR><Cmd>call vimrc#feat#ddu#ff#wait_start(v:false)<CR>
'''

[[plugins]]
repo = 'https://github.com/matsui54/ddu-source-help'
# L<ddu-local-help>
hook_add = '''
nnoremap dh <Cmd>Ddu -name=help<CR><Cmd>call vimrc#feat#ddu#ff#wait_start(v:true)<CR>
'''

[[plugins]]
repo = 'https://github.com/Shougo/ddu-column-filename'

[[plugins]]
repo = 'https://github.com/Shougo/ddu-commands.vim'
on_cmd = ['Ddu']

[[plugins]]
repo = 'https://github.com/Shougo/ddu-filter-matcher_substring'

[[plugins]]
repo = 'https://github.com/Shougo/ddu-filter-sorter_alpha'

[[plugins]]
repo = 'https://github.com/Shougo/ddu-kind-file'
# L<ddu-kind-file>

[[plugins]]
repo = 'https://github.com/Shougo/ddu-source-file_rec'

[[plugins]]
repo = 'https://github.com/Shougo/ddu-source-file'
hook_add = '''
nnoremap ;f <Cmd>Ddu file -name=file -source-option-_-path=`expand('%:p:h')` -searchPath=`expand('%:p')`<CR><Cmd>call vimrc#feat#ddu#ff#wait_start(v:false)<CR>z.
'''

[[plugins]]
repo = 'https://github.com/Shougo/ddu-source-line'
# L<ddu-local-line>
hook_add = '''
nnoremap dl <Cmd>Ddu -name=line<CR><Cmd>call vimrc#feat#ddu#ff#wait_start(v:true)<CR>
'''

[[plugins]]
repo = 'https://github.com/Shougo/ddu-ui-ff'

[[plugins]]
repo = 'https://github.com/Shougo/ddu-ui-filer'

[[plugins]]
repo = 'https://github.com/Shougo/ddu.vim'
# L<ddu-global>
hook_add = '''
autocmd User DenopsReady source $VIMDIR/conf/plug/ddu.vim
" DenopsReadyのタイミングが変わってて呼び出されなくなったので無理やり呼び出しておく
autocmd User DenopsReady ++once call timer_start(0, {->execute('doautocmd <nomodeline> User DenopsReady', '')})
'''

[[plugins]]
repo = 'https://github.com/shun/ddu-source-rg'
lazy = 1

[[plugins]]
repo = 'https://github.com/uga-rosa/ddu-source-lsp'
# X<toml-ddu_source_lsp>
hook_add = '''
if has('nvim')
  autocmd vimrc LspAttach * let b:ddu_source_lsp_clientName = 'nvim-lsp'
endif
autocmd vimrc User LspointsAttach:* let b:ddu_source_lsp_clientName = 'lspoints'
'''

[[plugins]]
repo = 'https://github.com/yuki-yano/ddu-filter-fzf'
# L<ddu-filter-matcher_fzf>

