[[plugins]]
repo = 'kuuote/ddu-source-git_diff'

[[plugins]]
repo = 'kuuote/ddu-source-git_status'
# L<ddu-source-git_status>
hook_add = '''
nnoremap gs <Cmd>call ddu#start({'name':'git_status','sourceOptions':{'_': {'path': expand('%:p')}}})<CR>
'''

[[plugins]]
repo = 'kuuote/ddu-source-mr'
# L<ddu-local-mr>
hook_add = '''
nnoremap mru <Cmd>call ddu#start({'name':'mru'})<CR>
nnoremap mrw <Cmd>call ddu#start({'name':'mrw'})<CR>
nnoremap mrr <Cmd>call ddu#start({'name':'mrr'})<CR>
'''

[[plugins]]
repo = 'kyoh86/ddu-filter-converter_hl_dir'
# L<ddu-filter-converter_hl_dir>

[[plugins]]
repo = 'Shougo/ddu-commands.vim'
on_cmd = ['Ddu']

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'

[[plugins]]
repo = 'Shougo/ddu-kind-file'
# L<ddu-kind-file>

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'

[[plugins]]
repo = 'Shougo/ddu-source-file'

[[plugins]]
repo = 'Shougo/ddu-source-line'
# L<ddu-local-line>
hook_add = '''
nnoremap dl <Cmd>call ddu#start({'name':'line'})<CR>
'''

[[plugins]]
repo = 'Shougo/ddu-ui-ff'

[[plugins]]
repo = 'Shougo/ddu-ui-filer'

[[plugins]]
repo = 'Shougo/ddu.vim'
# L<ddu-global>
hook_add = '''
call ddu#custom#load_config(expand('$VIMDIR/conf/plug/ddu/main.ts'))
call ddu#custom#load_config(expand('$VIMDIR/conf/plug/ddu/ff.ts'))
'''

[[plugins]]
repo = 'uga-rosa/ddu-source-lsp'
hook_add = '''
let g:ddu_source_lsp_clientName = 'lspoints'
'''

[[plugins]]
repo = 'yuki-yano/ddu-filter-fzf'
# L<ddu-filter-matcher_fzf>

