[[plugins]]
repo = 'https://github.com/denoland/deno_std'

[[plugins]]
repo = 'https://github.com/jsr-core/unknownutil'

[[plugins]]
repo = 'https://github.com/uga-rosa/deno-denops-lsputil'

[[plugins]]
repo = 'https://github.com/vim-denops/deno-denops-std'

