[[plugins]]
repo = 'https://github.com/Shougo/dpp-ext-installer'

[[plugins]]
repo = 'https://github.com/Shougo/dpp-ext-lazy'

[[plugins]]
repo = 'https://github.com/Shougo/dpp-ext-local'

[[plugins]]
repo = 'https://github.com/Shougo/dpp-ext-toml'

[[plugins]]
repo = 'https://github.com/Shougo/dpp-protocol-git'

[[plugins]]
repo = 'https://github.com/Shougo/dpp.vim'
# L<ddu-local-dpp>
hook_add = '''
nnoremap ;d <Cmd>call p#ddu#ff#start({'name':'dpp'})<CR>
'''

